name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: 
    steps:
      - name: Print greeting
        shell: pwsh
        run: |
          echo \
          "Hello World!"
      - name: Print goodbye
        shell: pwsh
        run: echo "Done - bye!"
      - name: Print all environmnet variables
        shell: pwsh
        run: set
      - name: Print secrets...
        shell: pwsh
        run: for s in ${{ secrets }} do; echo "Secret ${s}"; done
