name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        shell: pwsh
        run: |
          echo \
          "Hello World!"
      - name: Print goodbye
        shell: pwsh
        run: echo "Done - bye!"
      - name: Print all environmnet variables
        shell: pwsh
        run: dir "env:"
      - name: Print secrets...
        shell: pwsh
        run: foreach($s in ${{ secrets }}){echo "Secret ${s}"}
